{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "first-crud-fastapi.fullname" . }}-database
  labels:
   {{- include "first-crud-fastapi.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresql.instances }}
  
  {{- with .Values.postgresql.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ .Values.postgresql.storage.size }}
{{- end }}